import './globals.css';
import NavbarWrapper from '@/components/NavbarWrapper';
import FooterWrapper from '@/components/FooterWrapper';
import { CartProvider } from '@/context/CartContext';
import ReactQueryProvider from '@/components/ReactQueryProvider';
import { HeroUIProvider, ToastProvider } from '@heroui/react';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <ReactQueryProvider>
            <HeroUIProvider>
              <ToastProvider />
              <NavbarWrapper />
              {children}
              <FooterWrapper />
            </HeroUIProvider>
          </ReactQueryProvider>
        </CartProvider>
      </body>
    </html>
  )
}
